### ISSUE TITLE
Translation of the Livepeer and Streamflow white papers

### ISSUE THREAD

**Issue by ChuckChain** [Livepeer-Community-Node/Grant-Program#10]
**Proposal**
Hi @RaffiSapire, I'd like to propose the translation of the Livepeer white paper and the Streamflow white paper into German, Spanish and Swedish.

**Reason**
I'm proposing these languages to help Livepeer reach a wider audience. From reviewing the current issues, I understand that hackers are currently translating the white papers into French, Portuguese and Chinese, and I believe adding these three languages are a good complement to start (if there are instead other languages you'd like to prioritize, please let me know).

**Background & Skill**
I'm an early LPT delegator and fan of the project, and I would like to help the way I can. Since 2006, I run a side-business that includes a [Translation Agency](https://www.translationjm.com/). My team includes [remote translators](https://www.proz.com/blueboard/16169) from most countries, and we'd be happy to take this on.

**Timeframe**
**4 weeks total**: Translation into the three languages will be done concurrently, i.e.:

- 4 weeks: Translation of the [Livepeer white paper](https://github.com/livepeer/wiki/blob/master/WHITEPAPER.md) and the [Streamflow white paper](https://github.com/livepeer/wiki/blob/master/STREAMFLOW.md) into German
- 4 weeks: Translation of the [Livepeer white paper](https://github.com/livepeer/wiki/blob/master/WHITEPAPER.md) and the [Streamflow white paper](https://github.com/livepeer/wiki/blob/master/STREAMFLOW.md) into Spanish
- 4 weeks: Translation of the [Livepeer white paper](https://github.com/livepeer/wiki/blob/master/WHITEPAPER.md) and the [Streamflow white paper](https://github.com/livepeer/wiki/blob/master/STREAMFLOW.md) into Swedish

**Delivery**
The translations for each will live on GitHub by cloning the English format.

**Comment by RaffiSapire** [comment]
Hi there,

Awesome! I took a look at our google analytics, and it looks like the most popular countries are 1) China 2) Russia 3) Germany. I'd suggest starting here. For the Chinese translation, we have already had a community member do it, but we really need someone to proofread and make any suggestions, so would appreciate that as a grant if you have that skill in house. For the second two I've listed here, would be happy to give a grant as well. One thing we try to do is translate a paper, and build a community around it with the same person. For that reason, [translation grants](https://github.com/Livepeer-Community-Node/Grant-Program/issues/3) are typically paired with a series of community building activities. I'm not sure where you are based and if that is interesting to you?

**Comment by ChuckChain** [comment]
Hello,

Thanks for the reply!

**1. Chinese Proofreading**
Yes I do have someone who could proofread the Chinese translation here: [https://github.com/tonyjiang12399/wiki/blob/patch-1/WHITEPAPER_CHINESE.md](https://github.com/tonyjiang12399/wiki/blob/patch-1/WHITEPAPER_CHINESE.md). Let me know if you want us to proceed. Please allow us a week from start to get back to you with the proofread version and comments.

**2. Russian and German Translation**
We'd be happy to take care of the translations for both. As for the community aspect, I'm personally based in Canada and, while my translators are remote and usually based in the target country (e.g. Russia and Germany here), they would not be able to undertake the community building aspect unfortunately. So I can realistically only offer the translation part of the grants, and perhaps others will be able to take on the community building aspect using the translated whitepapers and other materials if needed.

**Comment by RaffiSapire** [comment]
Ok, yes please do review the Chinese translation. We will grant 50 LPT for this editing work. Please let us know when you will submit a final draft. 

For the Russian and German, let me get back to you when we are ready for this.

**Comment by ChuckChain** [comment]
Ok, the proofread Chinese translation will be ready early next week. Thanks.

**Comment by tonyjiang12399** [comment]
cool. thanks a lot.

**Comment by ChuckChain** [comment]
> Ok, yes please do review the Chinese translation. We will grant 50 LPT for this editing work. Please let us know when you will submit a final draft.
> 
> For the Russian and German, let me get back to you when we are ready for this.

I just sent you an email with the proofread translation. Thanks.

**Comment by RaffiSapire** [comment]
Thank you. Sent.

**Comment by ChuckChain** [comment]
Hi @RaffiSapire, the revised translation is now live:
https://github.com/ChuckChain/wiki/blob/master/WHITEPAPER%20-%20CHINESE.md

**Comment by RaffiSapire** [comment]
This has been paid, thank you ChuckChain! https://etherscan.io/tx/0x5f69aa649530bb9492cb9c8c391ac48b9ee8db9fe34395854c2d9634ab3c216d
