### ISSUE TITLE
Identity and Comments on Livepeer Explorer for a better Transcoder Experience

### ISSUE THREAD

**Issue by mattlockyer** [Livepeer-Community-Node/Grant-Program#11]
3Box is an open source project for user controlled profiles and messaging. Integrating 3Box into the Livepeer explorer would enrich the transcoder experience, while still keeping user profile data decentralized. Down the road, comments and custom data would create a rich meta layer of signal and reputation for transcoders.

**Describe the problem you are solving.** 
The Livepeer explorer currently lacks a personal feel to it. Transcoders are people or entities and they should have associated avatars and profile data users expect in a web based application. This is a community, it should feel like one.
![image](https://user-images.githubusercontent.com/321340/55761827-71b4d400-5a15-11e9-8541-a137c84a0273.png)

**Describe the solution you are proposing.** 
Import 3Box.js
Add profile hovers for each address (zero UI effort)
Add profile setters for each address (minimal UI effort)
Eventually, add custom UI elements to further integrate the user owned profile data into the Livepeer explorer so all users, even those without 3Box profiles, can benefit from a rich user experience.

**Describe the scope of the project including a rough timeline and milestones** 
Get on the Livepeer roadmap within the next 2 sprints for adding profile hovers. This is a virtually zero touch integration.

**Please estimate hours spent on project based on the above** 
Profile hovers: 1-2 hours
- add a call to 3Box API onHover over a hex address
Profile Integrations: 3-4 hours
- add a call to 3Box.js GetProfile for each transcoder address
- handle responses
- replace hex addresses and placeholder avatars with actual user profile data
Deeper profile integrations: 10-20 hours
- option to set profile data
- add tooltip / modal component that can update profile information
- add profile page to Livepeer transcoder explorer for comprehensive profile overviews and editing

Check out the 3Box.js API Docs for more info: https://github.com/3box/3box-js/blob/develop/README.md

**Comment by RaffiSapire** [comment]
Hi Matt, thank you very much for this proposal! Do you have an example of this work in practice I can look at?
Add profile hovers for each address (zero UI effort) - what happens when you hover? Where does it link to? Who needs to update the profile link? What information is needed? 
Add profile setters for each address (minimal UI effort) -- what is a profile setter? What would that enable? What is the transcoder onboarding process? 

Sounds like you can do this independently, but it'd probably take some time for one of us to review PRs, etc. Is that right? 
Wonder what 3box would mean for the ENS integration we've had pending; will we still need it?

**Comment by mattlockyer** [comment]
Hi Raffi, Example is up at https://3box.io/ and many more are coming from our partners. I will share along with update this shortly.

Profile hovers link to and bring in data/UI from IPFS pinning servers so you don't need to add any additional UI. See: https://medium.com/3box/introducing-profile-hovers-30bae578459e

The profile links could be updated by anyone. It's a simple onHover event that triggers the hover in the 3Box.js API.

What might be better for the transcoder and bonder experience is showing the profiles directly. This would involve calling the 3Box API "GetProfile(address)" method when the page loads (or component mounts) and then replacing ugly hex addresses and avatars with actual user names and profiles. I've updated the grant to detail this.

Profile setters would allow Transcoders to update their profiles directly from the explorer. This is a deeper integration and requires some UI/UX thinking. i.e. Where do they update their profile, what fields are they updating?

**Comment by RaffiSapire** [comment]
Hey there, lets hop on the phone and discuss. 
Please email me at raffi@livepeer.org

**Comment by RaffiSapire** [comment]
Hi there, this is being done through issue #17, and I will close this issue. Excited to get this done.
