### ISSUE TITLE
Livepeer Primer - An Interactive Microsite

### ISSUE THREAD

**Issue by adamsoffer** [Livepeer-Community-Node/Grant-Program#13]
## Give a 3 sentence description about this proposal.

This proposal describes "Livepeer Primer", an interactive microsite for introducing beginners to the Livepeer project. "Livepeer Primer" would explain, at a high level, what the Livepeer project is, the problems it solves, and how it works through storytelling, illustration, and data from the Livepeer subgraph. It would cover concepts such as transcoding, the role of orchestrators and delegators, the Livepeer token, staking, fees, rounds, and inflation in a fun and engaging way.

## Describe the problem you are solving.
Because Livepeer introduces so many novel concepts, it can be somewhat daunting for beginners to fully grasp and appreciate what Livepeer is and how it works. 

## Describe the solution you are proposing.
Currently, livepeer.org directs newcomers to a 4-minute Medium article called ["Livepeer For Beginners" ](https://medium.com/livepeer-blog/livepeer-for-beginners-3b49945c24a7) and a 2-minute video called ["Livepeer 101"](https://www.youtube.com/watch?v=Y_lammvup8M) which do an excellent job introducing the project. 

I propose we also make available a highly visual and interactive microsite called "Livepeer Primer" that leverages storytelling, illustration, and data from the Livepeer subgraph in an effort to cater to more visual learners, inspire more users to participate in the network and encourage more video engineers to build using the platform.

In terms of style and communication I suggest drawing inspiration from these educational microsites:

- [https://urbit.org/primer](https://urbit.org/primer)
- [https://cash.app/bitcoin](https://cash.app/bitcoin)
- [https://hardware-wallets.io](https://hardware-wallets.io)
- [https://weth.io](https://weth.io)
- [https://ethgas.io/](https://ethgas.io/) 

## Describe the scope of the project including a rough timeline and milestones

1. Outline ~5/13 
2. Wireframe ~5/20
3. Illustrations ~6/3~ ~6/24 (collaboration with illustrator [Kellie Pcolar](http://www.kellie-vibes.com))
4. Design ~6/10~ ~7/1
5. Build ~6/24~ ~7/8 (would be open source and could be hosted at https://livepeer.studio/primer)

(Deliverables attached to each milestone would be shared on this issue.)

## Please estimate hours spent on project based on the above

I estimate ~10 hours of work per week over the course of 6 weeks for a total of **60 hours**.

**Comment by RaffiSapire** [comment]
Hi Adam. This sounds great. Approved! 1100 for the 60 hours (using your rate + the Trailing Twelve Month Avg of the LPT price for march), plus know there is additional for an UX design work from Xuan and the illustrator as needed.

**Comment by adamsoffer** [comment]
Thanks, Raffi! I'm excited to begin work on this.

**Comment by adamsoffer** [comment]
Here is a [link](https://www.notion.so/adamsoffer/Livepeer-Primer-Outline-59aeff9581ac42759e9925c174b19cc2) to the Primer outline. It's open to comments and suggestions from all!

**Comment by adamsoffer** [comment]
Here is a [link](https://invis.io/X6S9B0AS24H#/365992770_Home) to the wireframe based on the above outline.

**Comment by RaffiSapire** [comment]
HI adam, I'm disbursing 3/5ths of the 1100 based on all the great work you've done so far. Excited to get this to the finish line! https://etherscan.io/tx/0x87841acae9e9e6296d82d2bf67accce2507afdf45dd9844bb4ea62f645a21c36

**Comment by RaffiSapire** [comment]
Congrats on finishing this. https://livepeer.org/primer/ It is fantastic. Congrats to you and Kellie for the great work.

**Comment by RaffiSapire** [comment]
https://etherscan.io/tx/0x34c0d2b6377b422bdc0cfcf2d22b353acfeb0c1ef52c53547c5a80a1974d8687

remaining sent
