### ISSUE TITLE
Live Stream Staking App - Staking Persona Study

### ISSUE THREAD

**Issue by xuan-yue** [Livepeer-Community-Node/Grant-Program#14]
**Give a 3 sentence description about this proposal.**
A 3D persona with validated learnings is foundational for redesigning the StreamFlow staking experience. I would like to gain a clearer understanding of the primary staking user's motivations and current behaviors. This persona study would document pains, gains, goals, as well as any behavioral, psychographic or demographic details that would serve as an anchoring point for design decisions.

**Describe the problem you are solving.** 
Currently, we do not have a clear idea of the persona we are designing for. Building out a validated 3D persona for the staker would help all designers coming to the project stay user-centric in their design decisions. 

**Related Issues**
https://github.com/Livepeer-Community-Node/Grant-Program/issues/4
https://github.com/Livepeer-Community-Node/Grant-Program/issues/12

**Describe the solution you are proposing.** 
There are two sets of research that will be done to clarify the persona that we are designing around:
1. Current user base (UX-oriented)
2. Future user base (Market-oriented)

Team: 
Xuan + Min-Si

Deliverables:
3D persona canvases for stakers on platform
Validated pain points, gains, and motivations

**Describe the scope of the project including a rough timeline and milestones** 
Research proposal:
Design team will conduct customer interviews and usability studies around 2 persona:

1. First-time LivePeer user who want to invest
2. First-time LivePeer user who is curious about the LP technology

**Research methods**

1.) Reach out to Livepeer team to brainstorm persona types
2.) Write out skeletal persona types, focus on goal + pain points
3.) Define which personas to design for
4.) Create + send screening survey to Alvin for distribution, recruit for study
5.) Iterate the interview guide with LP team
6.) Schedule 10 interviews (M / X - 5 each and share findings)
7.) Iterate the "ideal" beneficial to LP ecosystem segment with the LP team.

Schedule 10 customer discovery calls with pre-screened candidates.

_Customer Discovery_
  - Focus on discovering pains, gains, and motivations
  - Identify how closely this matches Early Adopter Rubric

_Staking Early Adopter_

Ask participants about staking behavior:
* Identify Early Adopter customer segments by 5 criteria: (i.e. a crypto-investor currently staking on other dApps)
    * Has the right pain point (i.e. low returns on staking crypto)
    * Aware of pain point (i.e. states unprompted that staking is unrewarding on another platform)
    * Has actively looked for a solution (i.e. sought out new platform to stake on within the last month)
    * Has hacked together a solution (i.e. has staked on multiple platforms to try them out)
    * Has paid for a solution (i.e. bought some amount of crypto in the past to stake on another platform)

_Milestone #1_
Completed persona brainstorming session, screening survey, interview guide, and skeletal personas; recruited and scheduled 10 participants for interviews.

_Milestone #2_
Completed 10 interviews, debriefed learnings with team, completed analysis (Affinity mapping, visualizations, etc). Created second iteration of personas (resegment if necessary). Update screening survey, interview guide, and persona canvas with validated learnings. Recruited and scheduled 5 - 10 (new or old) participants for refined interviews.

_Milestone #3_
Completed 5 - 10 second round interviews, completed refined persona canvases for 1 or 2 staker personas who are likely early adopters of the platform.

**Please estimate hours spent on project based on the above** 

40 research hours +20 analysis hours
5 hours revision buffer
**Total: 65 hours**

**Comment by RaffiSapire** [comment]
This has been completed.
