### ISSUE TITLE
Decentralized Profiles / Identities in the Explorer, via 3Box

### ISSUE THREAD

**Issue by S1nus** [Livepeer-Community-Node/Grant-Program#17]
**Give a 3 sentence description about this proposal.**
A simple profile system shall be added to the LivePeer explorer interface. The [3box](https://github.com/3box/3box) profiles API will be integrated, as it is a ready-to-go solution which provides sufficient functionality.

**Describe the problem you are solving.** 
The Explorer interface is a great way for those wishing to participate in the LivePeer network to browse and compare transcoders, as well as stake tokens and view transcoder statistics. However, at the moment, the only identifier for entities on the network are Ethereum addresses. For users new to the Ethereum ecosystem, this may be a barrier to entry. For this reason, a profile system allowing entities such as transcoders to supply their names, a profile picture, and other details about themselves is necessary.

**Describe the solution you are proposing.** 
Integrate 3box's "Profiles" API. 3box is an open-source project that aims to streamline the user experience of Dapps in regards to users' personal data. One of the APIs they have is for profiles. It's quite easy to set and retrieve profile data using their simple JavaScript API.

**Describe the scope of the project including a rough timeline and milestones** 
The project shall be completed within 8 weeks of the grant being approved. In addition to working on this 3box integration, I'll also work on other various tasks, such as:
* Taking minutes during research calls and translating them into forum posts.
* Fix 2-4 bugs with the LivePeer explorer per week.
* Reply to technical questions about the StreamFlow test network in the Discord within 20 minutes.
* Provide status updates twice per day, in the morning at ~9AM and in the evening at ~5PM, as well as 45-minute briefs per week with a LivePeer employee.

**Please estimate hours spent on project based on the above**
40 hours per week for 8 weeks

**Comment by S1nus** [comment]
Proposed milestones:

**Milestones:**
**June 30th**: Workflow for testing components
**July 3rd**: First-draft of first research summary article
**July 7th**: Create a component which detects the default profile of the user, either `3box` or `livepeer`.
**July 10th**: Final draft of first research summary article
**July 14th**: Create a component which displays the profile information of the user, either from `3box` space or `livepeer` space.
**July 17th**: First-draft of second research summary article
**July 21st**: Create a form to edit the profile information in either `3box` space or `livepeer` space
**July 24th**: Final draft of second research summary article
**July 28th**:  Moderation / block list system
**July 31st**: First draft of third research summary article
**August 4th**: Begin coding *link external transcoder account* functionality
**August 7th**: Final draft of third research summary article
**August 11th**: Continue development of *link external transcoder account* functionality

**Comment by S1nus** [comment]
**This week's update**:
* Git workflow established
* React / JavaScript workflow established
* Information gathered for article, work on first draft started

**Comment by S1nus** [comment]
**This Week's Update**:
* Working component which detects whether or not a profile has been set up
* Ability to display a default empty profile when none is set up
* Loading animation shows while interface waits for 3box data
* Groundwork laid for an "edit profile" form
* Code robustly and asynchronously handles changes in MetaMask accounts
* Rough draft of blog post completed

**Comment by RaffiSapire** [comment]
Hey Connor! Could you share your latest update, and timing on 3box integration please @S1nus ? please include links to the outputs for the deliverables, whethere they are linked to github, google doc, etc: 
June 30th: Workflow for testing components 
July 7th: Create a component which detects the default profile of the user, either 3box or livepeer. 
July 10th: Final draft of first research summary article
July 14th: Create a component which displays the profile information of the user, either from 3box space or livepeer space. 
July 17th: First-draft of second research summary article.

**Comment by S1nus** [comment]
Hi Raffi,
I have screenshots of the milestones:
 June 30th: Workflow for testing components
- [Parcel being used to test components](https://imgur.com/7u57EH0)

July 7th: Create a component which detects the default profile of the user, either 3box or livepeer.
July 14th: Create a component which displays the profile information of the user, either from 3box space or livepeer space.
- [Component displaying a 3box profile](https://imgur.com/hsZCJEn)
- [Component displaying a livepeer profile](https://imgur.com/m3mn1Tq)
- They are automatically detected and displayed

July 21st: Create a form to edit the profile information in either 3box space or livepeer space
- [Empty profile with "Set Up Profile Button"](https://imgur.com/kgDXz21)
- [Form to set up profile](https://imgur.com/fMNwZD7)
- [Loading animation after you click save](https://imgur.com/KVau3CO)
- [The newly saved profile](https://imgur.com/ucgxVyq)

I will message you about the research articles, and I will post another update tonight

**Comment by S1nus** [comment]
**This Week's Update**:
- Nearly all functionality in the [spec](https://www.notion.so/Livepeer-Bounty-2c7cb6ac7f7a4bb0a0c441cfdc6eec1a?d=17422e04-0105-485f-9efe-5c659213a404#f9d7804d5a4949ba879116d67480c907) for the "My Account" Page is done, spare the "Edit Profile" functionality
- We can detect whether the user has a 3box or a livepeer profile, and display it
- A user can click "Set Up Profile" and go to a form where they can upload a profile picture, set their name, bio, and website, and save it to the `livepeer` 3box space. A loading animation is displayed while it saves
- If the user has a 3box profile already, we can detect it, and an alert box pops up asking if they want to reuse it.
- The code has been refactored to best practices with React, pending a code review from @iameli for my most recent PR to the `3box` branch
- I created a [post](https://forum.livepeer.org/t/community-call-july-18th-2019/816) summarizing the Community Call on the Forum

**Comment by S1nus** [comment]
**Update**:
* You can view a user's profile under the "Account Overview" page in the explorer
* If it's your account, you can edit your profile. If it's a `livepeer` profile, it opens a form. If it's a `3box` profile, it brings you to 3box.io to edit your profile
* Transcoders listed on the Explorer show the profile picture and name, if they have one set

**ToDo List**:
* Better styling for My Account page
* "link external account" flow - I am going to need to dig into the Go codebase
* Need to do a quick bugfix for when certain parts of the profile are not set
* Blocklist in the works

![TranscoderCard basic info](https://i.imgur.com/54Hxnac.png)
