### ISSUE TITLE
 translate the white paper and steamflow whitepaper into Chinese

### ISSUE THREAD

**Issue by tonyjiang12399** [Livepeer-Community-Node/Grant-Program#9]
**Give a 3 sentence description about this proposal.**
 translate the white paper into Chinese
https://media.readthedocs.org/pdf/livepeer/latest/livepeer.pdf

**Describe the problem you are solving.** 
 translate the white paper into Chinese

**Describe the solution you are proposing.** 
 translate the white paper into Chinese

**Describe the scope of the project including a rough timeline and milestones** 
 translate the white paper into Chinese

**Please estimate hours spent on project based on the above** 
40 hours
[livepeer.pdf](https://github.com/Livepeer-Community-Node/Grant-Program/files/2989252/livepeer.pdf)

**Comment by RaffiSapire** [comment]
Thanks @tonyjiang12399 - We are happy to grant you a 150 LPT for a complete translation of the Livepeer whitepaper: https://github.com/livepeer/wiki/blob/master/WHITEPAPER.md

The output should be a translated document that lives in Github. You can clone the existing above and translate. Let us know if you have any questions!

**Comment by tonyjiang12399** [comment]
Thanks. Will update soon.

**Comment by tonyjiang12399** [comment]
https://github.com/tonyjiang12399/wiki/blob/patch-1/WHITEPAPER_CHINESE.md
Done.

**Comment by tonyjiang12399** [comment]
Can I translate https://github.com/livepeer/wiki/blob/master/STREAMFLOW.md as next step?

**Comment by tonyjiang12399** [comment]
https://github.com/tonyjiang12399/wiki/blob/master/STREAMFLOW.md

this is streamflow whitepaper

**Comment by RaffiSapire** [comment]
I have had two people review it and they have both told me that it seems like it has been done through a machine: 
"I feel the original translation may be machine translated as so many sentences are grammatically wrong and some words are obviously wrongly translated. Proofreading proves to be as difficult as re-translating." 
Therefore, we are not completing this grant nor are we open to considering future translations.
